language: go

os:
  - linux
  - osx

env:
  matrix:
    - ONIG_VERSION=5.9.6 MODE=STATIC
    - ONIG_VERSION=5.9.6 MODE=DYNAMIC
    - ONIG_VERSION=6.0.0 MODE=STATIC
    - ONIG_VERSION=6.0.0 MODE=DYNAMIC
    - ONIG_VERSION=DEFAULT

before_install:
  - |
    case "$ONIG_VERSION" in
    "DEFAULT")
        if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
            brew update ;
            brew install oniguruma ;
        elif [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
            sudo apt-get -qq update ;
            sudo apt-get install libonig-dev ;
        fi
        ;;
    *)
        curl -sLO https://github.com/kkos/oniguruma/releases/download/v${ONIG_VERSION}/onig-${ONIG_VERSION}.tar.gz ;
        tar xfz onig-${ONIG_VERSION}.tar.gz ;
        cd onig-${ONIG_VERSION} ;
        ./configure && make && make install ;
        ;;
    esac ;

install:
  - echo "Skipping install phase, because github.com/fstab/grok_exporter has all its dependencies in the vendor/ folder."

script:
  - go version
  - go test -v $(go list ./... | grep -v /vendor/)
  - go install .
  - ./integration-test.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go list ./... | grep -v /vendor/ | while read package ; do go test -covermode count -coverprofile=$(basename $package).coverprofile $package ; done ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gover && goveralls -coverprofile=gover.coverprofile -service=travis-ci ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm *.coverprofile ; fi

go:
  - tip
